import { test, expect, chromium } from '@playwright/test'
import { readFile } from 'node:fs/promises'
const publicCatalog = JSON.parse(await readFile('docs/public/catalog.json', 'utf8'))
async function publicUI(page) {
  await page.route('**/api/catalog', route => route.fulfill({ json: publicCatalog }))
  await page.goto('/')
  await expect(page.locator('.loading')).toHaveCount(0)
  await expect(page.locator('.repo-card').first()).toBeVisible()
}
test('live private inventory, README and no-store access', async ({ request }) => {
  const response = await request.get('/api/catalog', { timeout: 180000 })
  expect(response.ok()).toBeTruthy()
  expect(response.headers()['cache-control']).toBe('no-store')
  const data = await response.json()
  expect(data.scope).toBe('private')
  expect(data.repos.some(r => r.private)).toBeTruthy()
  expect(data.repos.length).toBeGreaterThan(publicCatalog.repos.length)
  expect(data.repos.every(r => ['ok', 'missing', 'error'].includes(r.readme.status))).toBeTruthy()
  expect(data.repos.every(r => r.categories.length > 0)).toBeTruthy()
  expect(data.repos.every(r => ['application', 'library', 'example', 'prototype', 'documentation', 'assets', 'placeholder'].includes(r.projectType))).toBeTruthy()
  expect(JSON.stringify(data)).not.toMatch(/gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}/)
  console.log(JSON.stringify({ total: data.repos.length, private: data.repos.filter(r => r.private).length, readmes: data.repos.filter(r => r.readme.status === 'ok').length, missingReadmes: data.repos.filter(r => r.readme.status === 'missing').length, failedReadmes: data.repos.filter(r => r.readme.status === 'error').length, missingPurpose: data.repos.filter(r => r.purposeSource === 'Pendente').length }))
})
test('foreign origins and host names cannot read local data', async ({ request }) => {
  expect((await request.get('/api/catalog', { headers: { Origin: 'https://attacker.invalid' } })).status()).toBe(403)
  expect((await request.get('/api/catalog', { headers: { Host: 'attacker.invalid:4188' } })).status()).toBe(403)
  expect((await request.post('/api/catalog')).status()).toBe(405)
  expect((await request.get('/api/readme?repo=not-owned')).status()).toBe(404)
  expect((await request.post('/api/annotations', { data: { name: 'catalogo', purpose: 'forged', categories: [] }, headers: { Origin: 'https://attacker.invalid' } })).status()).toBe(403)
})
test('personal purpose and categories save locally and survive a new request', async ({ page, request }) => {
  const data = await (await request.get('/api/catalog')).json()
  const before = data.repos.find(r => r.name === 'catalogo')
  await page.goto('/')
  await page.getByLabel('Buscar aplicações').fill('catalogo')
  await page.locator('.repo-card h3 button').click()
  await page.getByRole('button', { name: 'Editar ficha pessoal' }).click()
  const purpose = 'Biblioteca pessoal de aplicações com READMEs e categorias. Validação de curadoria.'
  try {
    await page.getByLabel('Para que serve esta aplicação?').fill(purpose)
    await page.getByRole('button', { name: 'Salvar ficha' }).click()
    await expect(page.locator('.detail-purpose')).toHaveText(purpose)
    const after = await (await request.get('/api/catalog')).json()
    expect(after.repos.find(r => r.name === 'catalogo').purpose).toBe(purpose)
    const file = JSON.parse(await readFile('.catalog/annotations.json', 'utf8'))
    expect(file.catalogo.purpose).toBe(purpose)
  } finally {
    await request.post('/api/annotations', { headers: { Origin: 'http://127.0.0.1:4188' }, data: before.purposeSource === 'Anotação pessoal' ? { name: 'catalogo', purpose: before.purpose, categories: before.categories } : { name: 'catalogo', reset: true } })
  }
})
test('search, filters, pagination and carousel open real documentation', async ({ page }) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await publicUI(page)
  await page.locator('.pagination').getByRole('button', { name: 'Próxima' }).click()
  await expect(page.locator('.pagination')).toContainText('2 /')
  await page.getByLabel('Buscar aplicações').fill('catalogo')
  await expect(page.locator('.repo-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Carrossel', exact: true }).click()
  await expect(page.locator('.carousel h3')).toHaveText('catalogo')
  await page.getByRole('button', { name: 'Conhecer aplicação e README' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.readme')).toContainText('Catálogo')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Limpar filtros' }).click()
  await page.locator('.carousel').focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.carousel-meta')).toContainText('2 /')
  expect(errors).toEqual([])
  await page.screenshot({ path: '.catalog/desktop-carousel.png', fullPage: true })
})
test('mobile layout, keyboard details and no overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await publicUI(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.locator('.repo-card h3 button').first().focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.repo-card h3 button').first()).toBeFocused()
  await page.screenshot({ path: '.catalog/mobile-library.png', fullPage: true })
})
test('README scripts, images and unsafe links are inert', async ({ page }) => {
  const repo = { ...publicCatalog.repos[0], name: 'security-fixture', readme: { status: 'ok', text: '<script>window.compromised=true</script>\n\n![tracker](https://attacker.invalid/tracker)\n\n[unsafe](javascript:alert(1))\n\n[relative](./guide.md)' } }
  await page.route('**/api/catalog', route => route.fulfill({ json: { ...publicCatalog, repos: [repo] } }))
  await page.goto('/')
  await page.locator('.repo-card h3 button').click()
  await expect(page.locator('.readme img')).toHaveCount(0)
  await expect(page.locator('.readme script')).toHaveCount(0)
  expect(await page.evaluate(() => window.compromised)).toBeUndefined()
  await expect(page.locator('.readme a')).toHaveCount(1)
  await expect(page.locator('.readme a')).toHaveAttribute('href', /https:\/\/github.com\/.*\/guide.md/)
})
test('service worker caches public catalog and works offline without caching private API', async ({ page, context }) => {
  await publicUI(page)
  await page.evaluate(async () => {
    const registration = await navigator.serviceWorker.ready
    if (!registration.active) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true }))
    await new Promise(resolve => setTimeout(resolve, 1000))
  })
  const cacheCheck = await page.evaluate(async () => {
    const keys = await caches.keys()
    const cached = (await Promise.all(keys.map(async k => (await (await caches.open(k)).keys()).map(r => r.url)))).flat()
    return { api: cached.some(u => u.includes('/api/')), catalog: cached.some(u => u.endsWith('/catalog.json')) }
  })
  expect(cacheCheck).toEqual({ api: false, catalog: true })
  await page.unroute('**/api/catalog')
  await context.setOffline(true)
  const cachedCatalog = await page.evaluate(async () => (await (await fetch('/catalog.json')).json()).repos.length)
  expect(cachedCatalog).toBe(publicCatalog.repos.length)
  await page.reload()
  await expect(page.getByText('Você está offline', { exact: false })).toBeVisible()
  await expect(page.locator('.repo-card')).toHaveCount(24)
  await expect(page.getByText('Somente repositórios públicos', { exact: false })).toBeVisible()
  await context.setOffline(false)
})
test('PWA manifest and installability are accepted by the browser', async () => {
  const context = await chromium.launchPersistentContext('.catalog/pwa-check-' + Date.now(), { channel: 'msedge', headless: true, baseURL: 'http://127.0.0.1:4188' })
  try {
    const page = await context.newPage()
    await publicUI(page)
    await page.evaluate(() => navigator.serviceWorker.ready)
    const session = await context.newCDPSession(page)
    const manifest = await session.send('Page.getAppManifest')
    expect(manifest.errors).toEqual([])
    const data = JSON.parse(manifest.data)
    expect(data.display).toBe('standalone')
    expect(data.icons.map(i => i.sizes)).toEqual(['192x192', '512x512'])
    const eligibility = await session.send('Page.getInstallabilityErrors')
    expect(eligibility.installabilityErrors).toEqual([])
  } finally { await context.close() }
})
